# Generated by Django 4.0.2 on 2022-05-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0007_repositories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IssuedBooks',
        ),
    ]
