# Generated by Django 4.0.2 on 2022-05-11 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicApp', '0010_alter_repositories_progress_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('commit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('textFile', models.URLField(blank=True)),
                ('videoFile', models.URLField(blank=True)),
                ('imageFile', models.ImageField(blank=True, upload_to='')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repoCommit', to='basicApp.repositories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repoCommiter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
