# Generated by Django 4.0.2 on 2022-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0012_commit_createddate_alter_commit_imagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='commitMsg',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
