# Generated by Django 4.0.2 on 2022-05-11 20:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0013_commit_commitmsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositories',
            name='id',
        ),
        migrations.AddField(
            model_name='repositories',
            name='repo_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
