# Generated by Django 4.0.2 on 2022-05-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0014_remove_repositories_id_repositories_repo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='imageFile',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='textFile',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='videoFile',
        ),
    ]
