# Generated by Django 4.0.2 on 2022-05-11 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicApp', '0015_remove_commit_createddate_remove_commit_imagefile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commit',
            name='imageFile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='repoCommit', to='basicApp.repositories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='textFile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='user',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='repoCommiter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='videoFile',
            field=models.URLField(blank=True),
        ),
    ]
